# -*- coding: utf-8 -*-
"""models.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1basc0q7R0EqRYECSBscPgemQlvRKqFNU
"""

import numpy as np
import pandas as pd

# Dummy forecast function for demo
def forecast_temperature_rainfall(city):
    # Demo 15-day forecast (random variation)
    temp = np.random.normal(28, 1.5, 15).tolist()
    rainfall = np.random.normal(110, 10, 15).tolist()
    days = [f"Day {i+1}" for i in range(15)]
    forecast_df = pd.DataFrame({
        "Day": days,
        "Temperature": temp,
        "Rainfall": rainfall
    })
    return forecast_df

