# -*- coding: utf-8 -*-
"""Untitled40.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1basc0q7R0EqRYECSBscPgemQlvRKqFNU
"""

import requests
import pandas as pd

API_KEY = "dd8fa47e1b055be7372aba4a11c85368"

# Fetch weather from OpenWeatherMap API (optional demo)
def fetch_weather(city):
    url = f"http://api.openweathermap.org/data/2.5/weather?q={city}&appid={API_KEY}&units=metric"
    response = requests.get(url).json()
    data = {
        "temperature": response['main']['temp'],
        "humidity": response['main']['humidity'],
        "weather": response['weather'][0]['description']
    }
    return data

# Crop recommendation based on temperature and rainfall
def recommend_crop(temp, rainfall):
    if rainfall > 120 and temp in range(25, 32):
        return "Soybean"
    elif rainfall < 100:
        return "Wheat"
    else:
        return "Maize"

